language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r test_requirements.txt
env:
- TEST_ENV=travis
script:
- flake8 . && travis_wait 50 py.test --nbval-lax
before_install:
- openssl aes-256-cbc -K $encrypted_39a50b90a369_key -iv $encrypted_39a50b90a369_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/.mdf/credentials/
- mv MDF_Forge_tokens.json ~/.mdf/credentials/MDF_Forge_tokens.json
after_success:
- coveralls
notifications:
  email:
    recipients:
    - jgaff@uchicago.edu
    on_success: never
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: vYpU1qxCSx8OMQsHBEfLZP6foqd88Xon54kejUNzMKR6BpOS0rgJZmY1VYKgqd8gWxAox3WyYDyIzEsEO/b0JQ4l53hC9A1Hk0F5YCTm9NjPIb0boIpJ2MbIuijnDAJEEiruevQKH+esmbOssGSg8bDyCd8V1vWrvCEe84pIbfsevIyuUnRWKpEIHk/oIDliUy9d8HhNJLGuJrKnIHtMFw+fkO36yQMxM5SDXuM6yvBXr3+7ntqeZXthYogmKLn1fu+X/V9v8Zz2MlfZmY9G5q3RSJAlC4ASeFLF8GNBZHsRBlGPvF8RNtRiiUlxXmYOes7B61SD3sHVAMvNhSS2xL0LGNU9ZzUWx8HVwlt60ATOF7aOu2Uao3SVWMi50ZC0DfRlUw11gNOyyMFq5zsHK32HeFm81o/TvSr/Iy4Xy8j/psX/38T9MjrgFxPneOolUIBjAeW27kW/39qfLLtPOqA3wmByucmiQTJXJhpIbiEKfnliERxbp5gGdFg0DZKQKWNikxjhUJXKU4EF5FC7m9KgqkgvfcnhhEoz6moRBDAjC9/xr9xIYFDa5bIYuB98gGWle452pUr3x5Br1SvS7RfA42Ob2G2U11T/GQ+uEmXy1Ai5emrxjF10qfXY1j7Oe1MbKNqR/C/n3Z3xjduX3LDSkskvcClqmi9cFuMX3Kk=
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: D94fhT0J3BQ29LdGJA0mvQiDZbuxapfMDkY99RaRf+VY/z9YlsvdSdyvlB/I01seyFQBJKma1sLJbpc+GRdcfd6NfILO7i27NgY0W+wJOafefUOOWhucmDX2PnnKSY+3PDnhlBI7Tn4lWcL7kzxp2TgUCc36VNhutg8PUQmA/+9H0HOh4q1oBWCaH+gNlQCA2XEYJ9KiBvrMJdZOPieo0JOWWhUlko8DVxttWXPW9ocww4jpHv4C7nHPFv8f7eFm6IDYmOT7gfBy8xK/B1iqQ78geGr/52zqNaU6f8KNTFJCu8XKNtv6nYXutPNlqkZoCwNjhW3rztO8ZbJRh6+oDSZlFrCsoRqGyGm4YDdvwyZQAFqsuwq8N47jMK1x0Xfe21d0QV5BElXvLkzRmMy++DdnRPrdvyyy2N5m3D4ZiMuBsClVzShT0wrBfs/w6+rDQTNjcEP6xqk0MHzScp2yBCk2mLERSd3oxtQ63OJYAagWgpPLC+yZVcLaH8CC9QfRoX+b+rHYQ46v0Z9k46q0LBoPt56NdTGGCXZLn8Zqr8hnliISnx2dOWneJ8gH0AlbNQDacU67sXmbgZMSdPrkcsZLzQOT8KqzUu8HhV1flodZKoeOKsqzzWk0Zo4LLvRLOqDox/p/X/Uj6rau3YOn6cn5sk0050BkeXnQhwwCMGk=
