language: python
python:
- '2.7'
#- '3.3'  # Bug in TravisCI prevents 3.3 tests running (old pip in path)
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install pytest pytest-cov coveralls flake8
env:
- TEST_ENV=travis
script:
- flake8 . && travis_wait 50 py.test
before_install:
- openssl aes-256-cbc -K $encrypted_39a50b90a369_key -iv $encrypted_39a50b90a369_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/.mdf/credentials/
- mv MDF_Forge_tokens.json ~/.mdf/credentials/MDF_Forge_tokens.json
after_success:
- coveralls
notifications:
  email:
    recipients:
    - jgaff@uchicago.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: vYpU1qxCSx8OMQsHBEfLZP6foqd88Xon54kejUNzMKR6BpOS0rgJZmY1VYKgqd8gWxAox3WyYDyIzEsEO/b0JQ4l53hC9A1Hk0F5YCTm9NjPIb0boIpJ2MbIuijnDAJEEiruevQKH+esmbOssGSg8bDyCd8V1vWrvCEe84pIbfsevIyuUnRWKpEIHk/oIDliUy9d8HhNJLGuJrKnIHtMFw+fkO36yQMxM5SDXuM6yvBXr3+7ntqeZXthYogmKLn1fu+X/V9v8Zz2MlfZmY9G5q3RSJAlC4ASeFLF8GNBZHsRBlGPvF8RNtRiiUlxXmYOes7B61SD3sHVAMvNhSS2xL0LGNU9ZzUWx8HVwlt60ATOF7aOu2Uao3SVWMi50ZC0DfRlUw11gNOyyMFq5zsHK32HeFm81o/TvSr/Iy4Xy8j/psX/38T9MjrgFxPneOolUIBjAeW27kW/39qfLLtPOqA3wmByucmiQTJXJhpIbiEKfnliERxbp5gGdFg0DZKQKWNikxjhUJXKU4EF5FC7m9KgqkgvfcnhhEoz6moRBDAjC9/xr9xIYFDa5bIYuB98gGWle452pUr3x5Br1SvS7RfA42Ob2G2U11T/GQ+uEmXy1Ai5emrxjF10qfXY1j7Oe1MbKNqR/C/n3Z3xjduX3LDSkskvcClqmi9cFuMX3Kk=
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ap4GShL/gmptUyRbJS6ZC7AY6WfdB08zt2KpkN5Qw7LAj7AxZLcPCc7Hr+bFpb3P3f5iOHcZHRXnKJhkr/nYw9QtBuVwcD8k6ZZzCCfXBTHrLOV6z1c6texRcuzYCG2lVCEMRmfBhryVWPrdswf6jnFt9+sWsNgTd0kVaj/BMumWWFH7S5MPckiQ0RSZfBrhNgQ1WZov5zMxotP5jJylOVPJeeNlKBpjvP1t2u8J+fYuogenNqdG2dGA2B3jIbrZUfhvVqGu7h7GOevPFoE0y4kC4X3WWnSS22KCxn038OdhqFmfW4MZRGJ9Xh9oWJDP3pKgJ3jSBrLYUKm240wVCoWvOsez8Ixxzit8jJYkzSE6foVSe4Xf12moHChjt4JqAY+Kj8uLe5IRAEwj/OrJcL2bjYhj+TkI+9yu8z8VaaxNRJim4B6GPeOOFXX/AkyOdXYgw0yZo0gNE3KmPJCvU6hAVIJAA1d0fZVWiyHCHH3AGOFNJChPXWbsnfGpganhAp660y9JFOQOeD9MCVF5CppY5/5QFhGIGilUuEZijWRBldcG70hDAeU9P6JNunnV2jvrpdfk5Z+0QkM4unJYGQcEnVU/gJWxN3335j5xWSgJR3qPsZ2G2vr8IL/LNLS3dj8S+xShpQChGMvD2ZtSYR4q97rC4guEjQydkfZjYSA=
